// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  status: __t.string(),
  roundId: __t.u64().name("round_id"),
  bombHolder: __t.option(__t.identity()).name("bomb_holder"),
  bombHolderSince: __t.u64().name("bomb_holder_since"),
  startedAtMicros: __t.u64().name("started_at_micros"),
  endsAtMicros: __t.u64().name("ends_at_micros"),
  durationSeconds: __t.u32().name("duration_seconds"),
  loserIdentity: __t.option(__t.identity()).name("loser_identity"),
  loserName: __t.option(__t.string()).name("loser_name"),
  lobbyEndsAtMicros: __t.u64().name("lobby_ends_at_micros"),
});
