// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Cursor = __t.object("Cursor", {
  identity: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  page: __t.string(),
  color: __t.string(),
  name: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Cursor = __Infer<typeof Cursor>;

export const ExplosionJob = __t.object("ExplosionJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roundId: __t.u64(),
});
export type ExplosionJob = __Infer<typeof ExplosionJob>;

export const HotPotatoGame = __t.object("HotPotatoGame", {
  id: __t.u64(),
  status: __t.string(),
  roundId: __t.u64(),
  bombHolder: __t.option(__t.identity()),
  bombHolderSince: __t.u64(),
  startedAtMicros: __t.u64(),
  endsAtMicros: __t.u64(),
  durationSeconds: __t.u32(),
  loserIdentity: __t.option(__t.identity()),
  loserName: __t.option(__t.string()),
  lobbyEndsAtMicros: __t.u64(),
});
export type HotPotatoGame = __Infer<typeof HotPotatoGame>;

export const LobbyJob = __t.object("LobbyJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roundId: __t.u64(),
});
export type LobbyJob = __Infer<typeof LobbyJob>;

export const ReadyPlayer = __t.object("ReadyPlayer", {
  identity: __t.identity(),
  roundId: __t.u64(),
});
export type ReadyPlayer = __Infer<typeof ReadyPlayer>;

export const Sweep = __t.object("Sweep", {
  scheduleId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type Sweep = __Infer<typeof Sweep>;

