// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Cursor = __t.object("Cursor", {
  identity: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  page: __t.string(),
  color: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Cursor = __Infer<typeof Cursor>;

