// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import SetCursorNameReducer from "../set_cursor_name_reducer";
import SweepIdleCursorsReducer from "../sweep_idle_cursors_reducer";
import UpdateCursorReducer from "../update_cursor_reducer";

export type SetCursorNameParams = __Infer<typeof SetCursorNameReducer>;
export type SweepIdleCursorsParams = __Infer<typeof SweepIdleCursorsReducer>;
export type UpdateCursorParams = __Infer<typeof UpdateCursorReducer>;

