// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ReadyUpReducer from "../ready_up_reducer";
import SetCursorNameReducer from "../set_cursor_name_reducer";
import StartHotPotatoReducer from "../start_hot_potato_reducer";
import UpdateCursorReducer from "../update_cursor_reducer";

export type ReadyUpParams = __Infer<typeof ReadyUpReducer>;
export type SetCursorNameParams = __Infer<typeof SetCursorNameReducer>;
export type StartHotPotatoParams = __Infer<typeof StartHotPotatoReducer>;
export type UpdateCursorParams = __Infer<typeof UpdateCursorReducer>;

